bin.includes = knime-streaming.jar,\
               META-INF/,\
               plugin.xml,\
               LICENSE.txt,\
               icons/,\
               CHANGELOG.md,\
               lib/lz4-java-1.10.3.jar,\
               lib/kafka-clients-3.9.1.jar,\
               lib/snappy-java-1.1.10.5.jar,\
               lib/zstd-jni-1.5.6-4.jar
jars.compile.order = knime-streaming.jar
source.knime-streaming.jar = src/
output.knime-streaming.jar = bin/
src.includes = LICENSE.txt,\
               lib/kafka-clients-3.9.1-sources.jar,\
               lib/lz4-java-1.10.3-sources.jar,\
               lib/snappy-java-1.1.10.5-sources.jar,\
               lib/zstd-jni-1.5.6-4-sources.jar
bin.excludes = maven.properties
